GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/all
Accept: application/json

###

POST http://localhost:8080/newUser
Content-Type: application/json

{
  "username": "Jack",
  "password": "654321",
  "age": 18
}

###

POST http://localhost:8080/updateAge/Rose/16
Content-Type: application/json

{}

###

POST http://localhost:8080/update
Content-Type: application/json

{
  "id": 2,
  "username": "Jack",
  "password": "23333",
  "age": 16
}

###


