GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/all
Accept: application/json

###

POST http://localhost:8080/newUser
Content-Type: application/json

{
  "username": "Jack",
  "password": "654321",
  "age": 18
}

###
